const data = [
  {
    id: 1,
    title: "brocoli",
    type: "vegatables",
    shortDescription: "fresh brocoli",
    content: "1kg",
    price: 3,
    status: "available",
    longDescription: "Fresh vegatable, quick service, trustful shopping",
    inCarousel: true,
    image: "../src/images/brocoli.jpg",
  },
  {
    id: 2,
    title: "eggs",
    type: "butchery-and-milk-products",
    shortDescription: "fresh eggs",
    content: "10 eggs",
    price: 3,
    status: "available",
    longDescription: "Fresh vegatable, quick service, trustful shopping",
    inCarousel: true,
    image: "../src/images/eggs.jpg",
  },
  {
    id: 3,
    title: "radish",
    type: "vegatables",
    shortDescription: "fresh radish",
    content: "1kg",
    price: 3,
    status: "available",
    longDescription: "Fresh vegatable, quick service, trustful shopping",
    inCarousel: true,
    image: "../src/images/radish.jpg",
  },
] as Product[];
export default data;
